{{- if .Values.followers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tile38.fullname" . }}-headless
  labels:
    {{- include "tile38.labels" . | nindent 4 }}
    role: follower
    {{- with .Values.followers.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.followers.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.followers.service.tilePort }}
      targetPort: tile
      protocol: TCP
      name: tile
  selector:
    {{- include "tile38.selectorLabels" . | nindent 4 }}
    role: follower
{{- end }}