{{- if .Values.followers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tile38.fullname" . }}-followers
  labels:
    {{- include "tile38.labels" . | nindent 4 }}
    role: follower
    {{- with .Values.followers.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.followers.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.followers.service.type  }}
  selector:
    {{- include "tile38.selectorLabels" . | nindent 4}}
    role: follower
  ports:
    - name: tile
      port: {{ .Values.followers.service.tilePort }}
      targetPort: tile
    - name: monitoring
      port: {{ .Values.followers.service.monitoringPort }}
      targetPort: monitoring
{{- end }}